#
# Module manifest for module 'ZENworksBundleMagement'
#
# Generated by: Tristan Schoonens
#
# Generated on: 28/06/2022
#

@{
    # Script module or binary module file associated with this manifest.
    RootModule        = 'ZENworksBundleManagement.psm1'
    
    # Version number of this module.
    ModuleVersion     = '0.1.0.1'
    
    # ID used to uniquely identify this module
    GUID              = '2e51d42e-50a0-4e52-9278-5eb19d0ca631'
    
    # Author of this module
    Author            = 'Tristan Schoonens'

    # Description of the functionality provided by this module
    Description       = 'Provides functions for creating and managing bundles in ZENworks Configuration Management.'

    RequiredModules = @('ZenworksZMAN')
    # Format files (.ps1xml) to be loaded when importing this module
    #FormatsToProcess  = @('ZENworksBundleManagement.Format.ps1xml')

    # Add any classes here to they are available.
    #ScriptsToProcess = @('Classes\ZENworksBundleAction.ps1','Classes\ZENworksBundleRequirement.ps1')

    # Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
    FunctionsToExport = @(
        "Add-ZENworksBundleAction",
        "Disable-ZENworksBundle",
        "Enable-ZENworksBundle",
        "Get-ZENworksBundle",
        'New-ZENworksBundle',
        'New-ZENworksBundleAssignment',
        'New-ZENworksBundleRequirements',
        'New-ZENworksBundleRequirementsFilter',
        'New-ZENworksBundleRequirementsGroup',
        'New-ZENworksBundleFileRemovalAction',
        'New-ZENworksBundleInstallBundleAction',
        'New-ZENworksBundleInstallExecutableAction',
        'New-ZENworksBundleInstallFilesAction',
        'New-ZENworksBundleInstallMSIAction',
        'New-ZENworksBundleLaunchAction',
        'New-ZENworksBundleRegistryEditAction',
        'New-ZENworksBundleServiceAction',
        'New-ZENworksBundleStopProcessAction',
        'New-ZENworksBundleArchitectureRequirement',
        'New-ZENworksBundleFileExistsRequirement',
        'New-ZENworksBundleProcessRunningRequirement',
        'New-ZENworksBundleRegistryKeyExistsRequirement',
        'New-ZENworksBundleRegistryKeyValueExistsRequirement',
        'New-ZENworksBundleRegistryKeyValueRequirement',
        'New-ZENworksBundleServiceExistsRequirement',
        'New-ZENworksBundleServiceRunningRequirement',
        'Publish-ZENworksBundle',
        'Remove-ZENworksBundle',
        'Remove-ZENworksBundleAction'
    )

    # Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
    PrivateData       = @{
        PSData = @{    
            # Tags applied to this module. These help with module discovery in online galleries.
            Tags       = @('ZENworks')
    
            # A URL to the license for this module.
            LicenseUri = 'https://github.com/trstns/ZENworksBundleManagement/blob/main/LICENSE'
    
            # A URL to the main website for this project.
            ProjectUri = 'https://github.com/trstns/ZENworksBundleManagement'
        }
    }
}
